### ISSUE TITLE
After installing to the system, the runnable command is not TimedPetriNetEditor but TimedPetriNetEditor-0.1.0

### ISSUE THREAD

**Issue by hurak** [Lecrapouille/TimedPetriNetEditor#8]
After `sudo make install`, what is actually copied to my `/usr/bin/` is

```bash
*** Installing: build/TimedPetriNetEditor => /usr/bin/TimedPetriNetEditor-0.1.0 
``` 
Therefore, after typing just `TimedPetriNetEditor` in the terminal, the command is not found. I have to type the full name of the file, which is `TimedPetriNetEditor-0.1.0`.  

No problem. Of couse, I can also create a symlink myself. It is just that now the instruction in README.md does not produce a desired outcome.

**Comment by Lecrapouille** [comment]
@hurak hi thanks I'll check if I have not a regression on my Makefile. The expected behavior is:
- /usr/bin/TimedPetriNetEditor-0.1.0 is the binary 
- /usr/bin/TimedPetriNetEditor is an alias to /usr/bin/TimedPetriNetEditor-0.1.0

this allows me to have several versions co-existing.

**Comment by Lecrapouille** [comment]
@hurak thank you. I missed creating the alias. Fixed now.
